theme = "catppuccin_mocha_transparent"

[editor]
evil = false
end-of-line-diagnostics = "hint"
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
G = "goto_file_end"
esc = ["collapse_selection", "keep_primary_selection"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after", "collapse_selection"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "collapse_selection"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
C-c = ":buffer-close"
0 = "goto_line_start"
J = "goto_next_paragraph"
K = ["goto_prev_paragraph", "extend_line_above"]
H = "goto_first_nonwhitespace"
L = "goto_line_end"
"C-/" = "toggle_comments"
i = ["collapse_selection", "insert_mode"]
a = ["collapse_selection", "append_mode"]
o = ["collapse_selection", "keep_primary_selection", "open_below"]
"O" = ["collapse_selection", "keep_primary_selection", "open_above"]
X = "extend_line_above"
V = ["extend_to_line_bounds", "select_mode"]
"C-\\" = ":sh zellij run -n Yazi -d Down -c --width 20%% --height 100%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
C-y = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"

[keys.normal.g]
n = "goto_next_change"
p = "goto_prev_change"

[keys.normal.";"]
w = ":write"
q = ":quit"

[keys.normal." "]
n = "goto_next_diag"
p = "goto_prev_diag"

[keys.select]
J = ["extend_line_below", "goto_next_paragraph"]
K = ["extend_line_above", "goto_prev_paragraph", "extend_line_above"]
o = ["collapse_selection", "keep_primary_selection", "open_below"]
"O" = ["collapse_selection", "keep_primary_selection", "open_above"]
i = ["collapse_selection", "insert_mode"]
a = ["collapse_selection", "append_mode"]
